import { useEffect, useState } from "react";
import { fetchDailySummary } from "../api/client";
import type { DailySummary } from "../types";
import Panel from "./Panel";

/**
 * A plain-English daily readout — every number in the sentence is real and
 * traceable to a specific query (see insights.service.ts). Assembled with a
 * template, NOT generated by an LLM; labelled "Daily Summary" rather than
 * "AI Summary" for exactly that reason.
 */
export default function DailySummaryPanel() {
  const [summary, setSummary] = useState<DailySummary | null>(null);
  const [error, setError] = useState(false);

  useEffect(() => {
    fetchDailySummary()
      .then(setSummary)
      .catch(() => setError(true));
  }, []);

  if (error) return null;
  if (!summary) return null;

  return (
    <Panel title="Daily summary" subtitle="Rule-based readout of today’s numbers — no AI involved">
      <p className="daily-summary__text">{summary.text}</p>
    </Panel>
  );
}
